User.create(name: "marco", email: "marco@marco.net", password: "123")
User.create(name: "salvador", email:"dali@dali.net", password: "123")
User.first.posts.create(body: "this is a body", url: "http://google.com")
User.first.comments.create(body: "this is a comment body")
User.first.posts.create(body: "this is a body", url: "http://google.com")
User.first.comments.create(body: "this is a comment body")
User.last.posts.create(body: "this is a body", url: "http://google.com")
User.last.comments.create(body: "this is a comment body")
User.last.posts.create(body: "this is a body", url: "http://google.com")
User.last.comments.create(body: "this is a comment body")
